version: "3.7"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: curl -f http://127.0.0.1:8000/api/health
      interval: 15s
      timeout: 10s
      retries: 3
    ports:
      - "8000:8000"
